---
abstract: 'Replace functions with ones that succeed or die with lexical scope'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autodie
no_index:
  directory:
    - inc
    - t
recommends:
  IPC::System::Simple: 0.12
requires:
  perl: 5.8.0
resources:
  Blog: http://pjf.id.au/blog/toc.html?tag=autodie
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=autodie
  license: http://dev.perl.org/licenses/
  repository: http://github.com/pfenwick/autodie/tree/master
version: 1.997
