---
abstract: 'Replace functions with ones that succeed or die with lexical scope'
author:
  - 'Copyright 2008, Paul Fenwick <pjf@perltraining.com.au>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: autodie
no_index:
  directory:
    - inc
    - t
recommends:
  IPC::System::Simple: 0.12
requires:
  perl: 5.10.0
version: 1.10_03
